=== ricardouriegas/sql_parser/exampleDTD.dtd
<!ELEMENT table (name, columns, primary_key?, foreign_key*, unique*, check*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT foreign_key (#PCDATA)>
<!ELEMENT columns (column+)>
<!ELEMENT column (name, type, primary_key?, unique?, not_null?, default?, check?)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT primary_key (#PCDATA)>
<!ELEMENT unique (#PCDATA)>
<!ELEMENT not_null (#PCDATA)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT check (#PCDATA)>

<!ATTLIST check column_name CDATA #REQUIRED>
<!ATTLIST check condition CDATA #REQUIRED>
<!ATTLIST foreign_key column_name CDATA #REQUIRED>
<!ATTLIST foreign_key referenced_table CDATA #REQUIRED>
<!ATTLIST foreign_key referenced_column CDATA #REQUIRED>

=== ricardouriegas/sql_parser/exampleXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "exampleDTD.dtd">

<table>
    <name>USERS</name>
    <columns>
        <column>
            <name>ID</name>
            <type>NUMBER</type>
            <primary_key></primary_key>
            <unique>TRUE</unique>
            <not_null>TRUE</not_null>
            <default>NULL</default>
            <check column_name="ID" condition="ID > 0"/>
        </column>
        <column>
            <name>USERNAME</name>
            <type>STRING</type>
            <check column_name="USERNAME" condition="LENGTH(USERNAME) > 0"/>
        </column>
        <column>
            <name>EMAIL</name>
            <type>STRING</type>
            <default>NULL</default>
        </column>
    </columns>
    <primary_key>USERNAME</primary_key>
    <foreign_key column_name="EMAIL" referenced_table="USERNAME" referenced_column="USERNAME"/>
    <unique>EMAIL</unique>
    <check column_name="ID" condition="ID > 0"/>
</table>
